### ISSUE TITLE
I use the dw1820a network card and how I should modify the aml file.

### ISSUE THREAD

**Issue by xxn10212** [Hackintoshlifeit/DELL-Optiplex-3060-MFF#1]
I use the dw1820a network card and how I should modify the aml file.

**Comment by Devil-66** [comment]
you have to change the arpt Dsm

**Comment by xxn10212** [comment]
![TIM图片20200924124854](https://user-images.githubusercontent.com/22068200/94102274-5ab1ae00-fe64-11ea-99da-fcf9bf97adfa.png)

I have modified the red box part in the picture, I don't know whether it is correct, please help me check it
 and i use bug sur

**Comment by xxn10212** [comment]
> you have to change the arpt Dsm.
> what version macos do you use? if use catalina, compatible Decice id 14e4 4331 you need to use, aspm set disabled From from bios.

I have modified the red box part in the picture, I don't know whether it is correct, please help me check it
and i use bug sur
![image](https://user-images.githubusercontent.com/22068200/94103318-f3492d80-fe66-11ea-9336-767e9d23d213.png)

**Comment by Devil-66** [comment]
> > you have to change the arpt Dsm.
> > what version macos do you use? if use catalina, compatible Decice id 14e4 4331 you need to use, aspm set disabled From from bios.
> 
> I have modified the red box part in the picture, I don't know whether it is correct, please help me check it
> and i use bug sur
[SSDT-HACK.aml.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273868/SSDT-HACK.aml.zip)
test this with boot args :  brcmfx-driver=2

[SSDT-HACK.aml 2.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273871/SSDT-HACK.aml.2.zip)
and test this together with bootargs : brcmfx-driver=2

**Comment by xxn10212** [comment]
> > > you have to change the arpt Dsm.
> > > what version macos do you use? if use catalina, compatible Decice id 14e4 4331 you need to use, aspm set disabled From from bios.
> > 
> > 
> > I have modified the red box part in the picture, I don't know whether it is correct, please help me check it
> > and i use bug sur
> > [SSDT-HACK.aml.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273868/SSDT-HACK.aml.zip)
> > test this with boot args :  brcmfx-driver=2
> 
> [SSDT-HACK.aml 2.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273871/SSDT-HACK.aml.2.zip)
> and test this together with bootargs : brcmfx-driver=2

![image](https://user-images.githubusercontent.com/22068200/94111185-49719d00-fe76-11ea-8025-02c185dca1d3.png)

This is right. Thank you very much

**Comment by Devil-66** [comment]
> > > > you have to change the arpt Dsm.
> > > > what version macos do you use? if use catalina, compatible Decice id 14e4 4331 you need to use, aspm set disabled From from bios.
> > > 
> > > 
> > > I have modified the red box part in the picture, I don't know whether it is correct, please help me check it
> > > and i use bug sur
> > > [SSDT-HACK.aml.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273868/SSDT-HACK.aml.zip)
> > > test this with boot args :  brcmfx-driver=2
> > 
> > 
> > [SSDT-HACK.aml 2.zip](https://github.com/Hackintoshlifeit/DELL-Optiplex-3060-MFF/files/5273871/SSDT-HACK.aml.2.zip)
> > and test this together with bootargs : brcmfx-driver=2
> 
> ![image](https://user-images.githubusercontent.com/22068200/94111185-49719d00-fe76-11ea-8025-02c185dca1d3.png)
> 
> This is right. Thank you very much

great, you solved.
