### ISSUE TITLE
BIOS settings and latest CPU Turbo support

### ISSUE THREAD

**Issue by scolar-yang** [Hackintoshlifeit/DELL-Optiplex-3060-MFF#2]
The latest Opencore seems to support CPU Turbo Boost & Thermal Throttling.
And can you please help to update and for better CPU Turbo support.
BTW: please help to write down how to set the BIOS settings.

Reference Link for DELL 7060 MFF:
https://github.com/webleon/Hackintosh-OptiPlex-7060-MFF

**Comment by Lorys89** [comment]
> The latest Opencore seems to support CPU Turbo Boost & Thermal Throttling.
> And can you please help to update and for better CPU Turbo support.
> BTW: please help to write down how to set the BIOS settings.
> 
> Reference Link for DELL 7060 MFF:
> https://github.com/webleon/Hackintosh-OptiPlex-7060-MFF

bios setting o cfg lock?

**Comment by scolar-yang** [comment]
> > The latest Opencore seems to support CPU Turbo Boost & Thermal Throttling.
> > And can you please help to update and for better CPU Turbo support.
> > BTW: please help to write down how to set the BIOS settings.
> > Reference Link for DELL 7060 MFF:
> > https://github.com/webleon/Hackintosh-OptiPlex-7060-MFF
> 
> bios setting o cfg lock?

Do not know, I saw the details on the link for bios settings for a better experience especially for starters.
